#Version 1.02
Listen placeholderip:8080

<Directory /var/www/html/placeholder/public_html>
        Options -Indexes -FollowSymLinks -MultiViews
        AllowOverride All
        Require all granted
	# Turn mod_rewrite on
	RewriteEngine On
	RewriteBase /
	# For LocalHost !.php
	#RewriteCond %{HTTP_HOST} !=localhost
	#RewriteCond %{HTTP_HOST} !=127.0.0.1
	#RewriteCond %{REMOTE_ADDR} !=127.0.0.1
	#RewriteCond %{REMOTE_ADDR} !=::1
	## hide .php extension
	# To externally redirect /dir/foo.php to /dir/foo
	RewriteCond %{THE_REQUEST} ^[A-Z]{3,}\s([^.]+)\.php [NC]
	RewriteRule ^ %1 [R=302,L]
	# To internally forward /dir/foo to /dir/foo.php
	RewriteCond %{REQUEST_FILENAME} !-d
	RewriteCond %{REQUEST_FILENAME}.php -f
	RewriteRule ^(.*?)/?$ $1.php [L]
	#Use a php file to manage urls
	#RewriteCond %{SCRIPT_FILENAME} !-f  #REMOVED TO RESTRICT ALL PATHS TO serve.php
	RewriteRule ^(.*)$ serve.php?path=$1 [QSA]
</Directory>

<Directory /var/www/html/placeholder_test/public_html>
        Options -Indexes -FollowSymLinks -MultiViews
        AllowOverride All
        Require all granted
	# Turn mod_rewrite on
	RewriteEngine On
	RewriteBase /
	# For LocalHost !.php
	#RewriteCond %{HTTP_HOST} !=localhost
	#RewriteCond %{HTTP_HOST} !=127.0.0.1
	#RewriteCond %{REMOTE_ADDR} !=127.0.0.1
	#RewriteCond %{REMOTE_ADDR} !=::1
	## hide .php extension
	# To externally redirect /dir/foo.php to /dir/foo
	RewriteCond %{THE_REQUEST} ^[A-Z]{3,}\s([^.]+)\.php [NC]
	RewriteRule ^ %1 [R=302,L]
	# To internally forward /dir/foo to /dir/foo.php
	RewriteCond %{REQUEST_FILENAME} !-d
	RewriteCond %{REQUEST_FILENAME}.php -f
	RewriteRule ^(.*?)/?$ $1.php [L]
	#Use a php file to manage urls
	#RewriteCond %{SCRIPT_FILENAME} !-f  #REMOVED TO RESTRICT ALL PATHS TO serve.php
	RewriteRule ^(.*)$ serve.php?path=$1 [QSA]
</Directory>

<VirtualHost placeholderip:80>
        ServerName placeholdersite
        DirectoryIndex index.php index.html
        DocumentRoot /var/www/html/placeholder/public_html
        ErrorLog /var/www/html/placeholder/logs/error.log
        CustomLog /var/www/html/placeholder/logs/access.log combined
</VirtualHost>

<VirtualHost placeholderip:80>
        ServerName test.placeholdersite
        DirectoryIndex index.php index.html
        DocumentRoot /var/www/html/placeholder_test/public_html
        ErrorLog /var/www/html/placeholder_test/logs/error.log
        CustomLog /var/www/html/placeholder_test/logs/access.log combined
</VirtualHost>
