<?php
/**
 * RelaySsh - the one place the tunnel's SSH/rsync command lines are built.
 *
 * The relay's whole network surface is Postfix + WireGuard + key-only SSH
 * (specs/inbound_email_hardened_ingest_relay_executor.md), so both the alias-map
 * push and the spool pull reach it over SSH on the WireGuard interface. This
 * centralises the connection flags (batch mode, accept-new host key, timeout,
 * port, identity file, login user) so the two consumers can never drift.
 *
 * The login is the deployment's RESTRICTED TENANT ACCOUNT (jt-<slug>, locked to
 * the joinery-tenant-shell forced command on the relay) — never root. What the
 * account can do is exactly the tenant surface: rsync pull of its own spool,
 * rsync push into its own fragment drop area, joinery-ack, joinery-merge,
 * joinery-ping (specs/mailbox_relay_shared_fleet.md § Multi-tenancy on a shard).
 *
 * @version 1.4 - $runner: the injectable command runner lives here, on the one
 *                execution chokepoint, not on individual callers
 * @version 1.3 - forgetHostKey(): a rebuilt relay reuses the tunnel address with
 *                a new host key, which accept-new refuses until the old one goes
 * @version 1.2 - login derives from the relay row's tenant identity (pullUser);
 *                the root default is gone
 */

require_once(PathHelper::getIncludePath('plugins/mailbox/data/mailbox_relay_class.php'));

class RelaySsh {

	/**
	 * The relay pull key: a dedicated SSH identity OWNED BY THE WEB USER, because
	 * every steady-state relay connection (spool pull, map push, health battery)
	 * runs as the web user — cron tasks and admin-page checks — and ssh refuses a
	 * key file its caller does not own with mode 600. Generated by
	 * provision_relay_main.sh (root, chowns to the web user); its public half is
	 * installed on the relay by the provision job. The admin/node key used to
	 * CREATE the relay never needs to be web-user-readable at all.
	 */
	public static function pullKeyPath(): string {
		return PathHelper::getSiteRoot() . '/config/relay_pull_key';
	}

	/** Common ssh options both ssh and rsync-over-ssh use. */
	private static function options(MailboxRelay $relay): array {
		$opts = array('-o', 'BatchMode=yes', '-o', 'StrictHostKeyChecking=accept-new', '-o', 'ConnectTimeout=15');
		$port = intval($relay->get('mrl_ssh_port'));
		if ($port > 0 && $port !== 22) {
			$opts[] = '-p';
			$opts[] = (string)$port;
		}
		$key = trim((string)$relay->get('mrl_ssh_key_path'));
		if ($key !== '') {
			$opts[] = '-i';
			$opts[] = $key;
		}
		return $opts;
	}

	public static function host(MailboxRelay $relay): string {
		return trim((string)$relay->get('mrl_host'));
	}

	public static function user(MailboxRelay $relay): string {
		return $relay->pullUser();
	}

	/**
	 * A ready-to-run `ssh ... -l user host <remote-command>` line, fully shell
	 * quoted. $remote_command is escaped as a single argument.
	 */
	public static function sshCommand(MailboxRelay $relay, string $remote_command): string {
		$parts = array_merge(array('ssh'), self::options($relay), array('-l', self::user($relay), self::host($relay)));
		return implode(' ', array_map('escapeshellarg', $parts)) . ' ' . escapeshellarg($remote_command);
	}

	/**
	 * An `rsync ... -e <ssh> <src> <user@host:dst>` line. $download flips the
	 * direction (remote→local). rsync always COPIES — never --remove-source-files,
	 * so a pull can never delete before durability.
	 */
	public static function rsyncCommand(MailboxRelay $relay, string $local, string $remote, bool $download, array $extra = array()): string {
		// rsync -e wants a plain command line it splits on spaces (not per-token
		// quoted); paths here are space-free. The whole thing is escaped once below.
		$transport = implode(' ', array_merge(array('ssh'), self::options($relay)));
		$remote_spec = self::user($relay) . '@' . self::host($relay) . ':' . $remote;

		$args = array('rsync', '-az', '--timeout=30');
		$args = array_merge($args, $extra);
		$args[] = '-e';
		$args[] = $transport;
		if ($download) {
			$args[] = $remote_spec;
			$args[] = $local;
		} else {
			$args[] = $local;
			$args[] = $remote_spec;
		}
		return implode(' ', array_map('escapeshellarg', $args));
	}

	/** @var callable|null fn(string $cmd): array{0:int,1:string} — test seam.
	 * THE seam, singular: every relay command line (provisioner, spool pull,
	 * map push, ping, forgetHostKey) executes through run(), so installing a
	 * scripted runner here intercepts all of it. A second seam elsewhere is how
	 * a real rsync once escaped a fully-scripted test and spent 15 seconds
	 * timing out against the tunnel address. */
	public static $runner = null;

	/** Run a shell command, returning [exit_code, combined_output]. */
	public static function run(string $cmd): array {
		if (self::$runner !== null) {
			return call_user_func(self::$runner, $cmd);
		}
		$output = array();
		$code = 0;
		exec($cmd . ' 2>&1', $output, $code);
		return array($code, implode("\n", $output));
	}

	/**
	 * Forget the host key recorded for a tunnel address.
	 *
	 * Every relay answers on the SAME fixed tunnel address (10.99.0.1), but a
	 * rebuilt relay is a NEW machine presenting a NEW SSH host key. The
	 * accept-new policy above learns an unknown host automatically and REFUSES a
	 * changed one, so unless the previous machine's key is forgotten at the
	 * moment the address changes hands, every rebuild breaks the map push and
	 * the spool pull with REMOTE HOST IDENTIFICATION HAS CHANGED. This is the
	 * SSH-identity half of replacing the WireGuard peer: same address, new
	 * machine, so the old identity has to go.
	 *
	 * Called when a relay row is bound to a new machine. Best-effort: a failure
	 * is logged, and the health checks surface the connection error.
	 */
	public static function forgetHostKey(string $host): void {
		$host = trim($host);
		if ($host === '') {
			return;
		}
		$home = '';
		if (function_exists('posix_geteuid') && function_exists('posix_getpwuid')) {
			$pw = @posix_getpwuid(posix_geteuid());
			if (is_array($pw) && !empty($pw['dir'])) {
				$home = (string)$pw['dir'];
			}
		}
		if ($home === '') {
			$home = (string)getenv('HOME');
		}
		if ($home === '') {
			error_log('RelaySsh::forgetHostKey: no home directory for the web user — '
				. 'stale host key for ' . $host . ' left in place.');
			return;
		}
		$known = $home . '/.ssh/known_hosts';
		if (!is_file($known)) {
			return; // nothing learned yet; accept-new will record the new key
		}
		list($code, $out) = self::run('ssh-keygen -f ' . escapeshellarg($known)
			. ' -R ' . escapeshellarg($host));
		if ($code !== 0) {
			error_log('RelaySsh::forgetHostKey: ssh-keygen -R failed for ' . $host . ': ' . $out);
		}
	}
}
