#!/usr/bin/php
<?php
/**
 * render_pgsql_map.php — prints the Postfix pgsql map that resolves the live
 * list of active email-forwarding domains.
 *
 * Standalone CLI helper (like utils/email_forwarder.php). It deliberately does
 * NOT bootstrap the Joinery framework: install_email.sh runs it as root, and a
 * full bootstrap as root risks creating root-owned cache/log files that later
 * break the www-data web process. It reads the database connection values
 * straight out of config/Globalvars_site.php instead.
 *
 * Output goes to stdout; install_email.sh redirects it into
 * /etc/postfix/joinery-domains.cf and locks the file down (640 root:postfix).
 * The map necessarily contains the database password — never echo it elsewhere.
 *
 * Usage:  php render_pgsql_map.php [/path/to/Globalvars_site.php]
 *
 * See specs/implemented/email_forwarding_install_unification.md (§6.2).
 *
 * @version 1.0
 */

// config/Globalvars_site.php sits alongside public_html, four directory levels
// up from this script's provisioning/ directory. An explicit path may be
// passed as argv[1] (used for testing).
$config_file = $argv[1] ?? (dirname(__DIR__, 4) . '/config/Globalvars_site.php');

if (!is_file($config_file) || !is_readable($config_file)) {
	fwrite(STDERR, "render_pgsql_map: cannot read config file: {$config_file}\n");
	exit(1);
}

/**
 * Globalvars_site.php is a list of `$this->settings['key'] = ...;` assignments
 * meant to be require'd inside the Globalvars constructor. Reading it inside a
 * method of this tiny shim reproduces just enough of that context to capture
 * the settings — without loading Globalvars or anything else.
 */
final class GlobalvarsSiteReader {
	public $settings = array();
	public function loadFrom($file) {
		require $file;
	}
}

$reader = new GlobalvarsSiteReader();
$reader->loadFrom($config_file);

$dbname = $reader->settings['dbname'] ?? '';
$dbuser = $reader->settings['dbusername'] ?? '';
$dbpass = $reader->settings['dbpassword'] ?? '';

if ($dbname === '' || $dbuser === '') {
	fwrite(STDERR, "render_pgsql_map: dbname/dbusername missing from {$config_file}\n");
	exit(1);
}

// The platform connects to PostgreSQL on localhost (see includes/DbConnector.php):
// the host is fixed, only the credentials and database name come from the file.
$lines = array();
$lines[] = '# Postfix pgsql map — active email-forwarding domains.';
$lines[] = '# Generated by render_pgsql_map.php; regenerate by re-running install_email.sh.';
$lines[] = 'hosts = localhost';
$lines[] = 'user = ' . $dbuser;
$lines[] = 'password = ' . $dbpass;
$lines[] = 'dbname = ' . $dbname;
// This query is the single definition of "active forwarding domain" and must
// stay aligned with the EmailForwardingDomain model (spec §7.3). lower() on the
// column side also covers any row written by a path that bypassed prepare().
$lines[] = "query = SELECT efd_domain FROM efd_email_forwarding_domains"
	. " WHERE lower(efd_domain) = '%s' AND efd_is_enabled = true AND efd_delete_time IS NULL";

echo implode("\n", $lines) . "\n";
exit(0);
