<?php
/* THIS FILE CONTAINS ALL SCRIPTS THAT ARE RUN UPON A PRODUCT PURCHASE
SET THE FUNCTION NAME WHEN CREATING THE PRODUCT  
ALL FUNCTIONS END WITH PRODUCT_SCRIPT
ALL FUNCTIONS MUST TAKE USER/PRODUCT/ORDER/ORDER_ITEM/CART  
*/
/*
function sample_product_script($user, $product, $order, $order_item, $cart){
	
	return true;
}
*/
?>

