//! jd-platform — the operating system, everywhere it is not the filesystem.
//!
//! `jd-vfs` owns the differences between filesystems. This crate owns the rest
//! of them: where a credential is safe, where a config file belongs, how a
//! background program gets started at login, how a URL reaches the user's
//! browser, and how one of the user's own processes reaches another. Five small
//! problems that have three answers each, kept together so that the daemon reads
//! the same on every platform.
//!
//! It also deliberately depends on nothing of the engine. That is what lets the
//! tray — which needs the control channel and none of the rest — be compiled for
//! macOS and Windows from a Linux box, and therefore be checked at all.
//!
//! The rule throughout is the same one the engine follows: **say what actually
//! happened**. A keychain that is not available produces a file and a reported
//! downgrade, not a silent one. An autostart artifact is generated by a pure
//! function so the exact text a Mac will load can be read in a test on Linux —
//! which matters because none of these failures are loud. A malformed plist does
//! not raise an error; it simply never starts.

pub mod autostart;
pub mod browser;
pub mod control;
pub mod dirs;
pub mod secret;

pub use autostart::{launch_agent_plist, systemd_user_unit, AutostartError};
pub use browser::open_url;
pub use control::{ControlServer, Endpoint};
pub use dirs::{default_sync_root, home_dir, Paths, APP_NAME, BINARY_NAME, BUNDLE_ID};
pub use secret::{Custody, Secret, SecretError, SecretStore};

/// What this build calls itself to the server, for the `client_app` identifier
/// and the upgrade gate.
pub const fn client_app() -> &'static str {
    #[cfg(target_os = "macos")]
    {
        "joinery-sync-macos"
    }
    #[cfg(target_os = "windows")]
    {
        "joinery-sync-windows"
    }
    #[cfg(not(any(target_os = "macos", target_os = "windows")))]
    {
        "joinery-sync-linux"
    }
}

/// The platform name the server records on the device row.
pub const fn platform_name() -> &'static str {
    #[cfg(target_os = "macos")]
    {
        "macos"
    }
    #[cfg(target_os = "windows")]
    {
        "windows"
    }
    #[cfg(not(any(target_os = "macos", target_os = "windows")))]
    {
        "linux"
    }
}

/// A name for this device that a person will recognize in a list of devices.
///
/// The machine's own name where it has one, because "MacBook Pro" in the
/// security page is the whole point — a user revoking a lost laptop has to be
/// able to tell which row is the laptop.
pub fn suggested_device_name() -> String {
    for var in ["JOINERY_DEVICE_NAME", "HOSTNAME", "COMPUTERNAME"] {
        if let Ok(v) = std::env::var(var) {
            let v = v.trim();
            if !v.is_empty() {
                return v.to_string();
            }
        }
    }
    // `HOSTNAME` is a shell variable rather than an exported one on most Linux
    // systems, so the file is the reliable source there.
    if let Ok(v) = std::fs::read_to_string("/etc/hostname") {
        let v = v.trim();
        if !v.is_empty() {
            return v.to_string();
        }
    }
    format!("{APP_NAME} ({})", platform_name())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn the_client_identifier_matches_the_platform_it_was_built_for() {
        assert!(client_app().starts_with("joinery-sync-"));
        assert!(client_app().ends_with(platform_name()));
    }

    #[test]
    fn a_device_name_is_never_empty() {
        // It ends up in conflict-copy filenames, where an empty one produces
        // `Report (conflicted copy 2026-07-31 from ).xlsx`.
        std::env::set_var("JOINERY_DEVICE_NAME", "  ");
        let name = suggested_device_name();
        std::env::remove_var("JOINERY_DEVICE_NAME");
        assert!(!name.trim().is_empty());
    }

    #[test]
    fn an_explicit_device_name_wins() {
        std::env::set_var("JOINERY_DEVICE_NAME", "Kitchen iMac");
        let name = suggested_device_name();
        std::env::remove_var("JOINERY_DEVICE_NAME");
        assert_eq!(name, "Kitchen iMac");
    }
}
