#!/usr/bin/php
<?php
/**
 * render_pgsql_map.php — prints one of the two Postfix pgsql maps a colocated
 * mail host reads:
 *
 *   domains           the live list of active inbound email domains
 *                     (virtual_mailbox_domains)
 *   recipient_access  the verdict on one recipient address while the sender
 *                     is still connected (check_recipient_access): accepted,
 *                     refused as "no such address", or left to the router
 *
 * Standalone CLI helper, invoked by install_email.sh. The Postfix map
 * authenticates as a dedicated least-privilege PostgreSQL role (not the
 * application's superuser): install_email.sh creates that role and supplies it
 * here as argv[1], with its password in the IEMAP_PASSWORD environment
 * variable — never argv, so the secret cannot appear in the process list. The
 * only thing read from config/Globalvars_site.php is the non-secret dbname.
 *
 * Output goes to stdout; install_email.sh redirects it into
 * /etc/postfix/joinery-domains.cf or /etc/postfix/joinery-recipient-access.cf
 * and locks the file down (640 root:postfix).
 *
 * Usage:  IEMAP_PASSWORD=... php render_pgsql_map.php <role> [/path/to/Globalvars_site.php] [domains|recipient_access]
 *
 * See specs/implemented/email_forwarding_pgsql_credential.md.
 *
 * The map is a live query — Postfix runs it per lookup, so domain AND
 * forwarding-subdomain changes take effect without re-rendering. Re-running
 * install_email.sh (which regenerates this file) is only needed to pick up a
 * query-shape change, or, with the map files deleted first, to rotate the role
 * password.
 *
 * @version 1.5 - neither map answers for an IMAP-feed anchor domain (gmail.com): this box does not
 *                receive its mail
 * @version 1.4 - the recipient_access map: unknown recipients are refused during the SMTP
 *                conversation instead of bounced afterwards
 * @version 1.3
 */

$role = $argv[1] ?? '';
if ($role === '') {
	fwrite(STDERR, "render_pgsql_map: missing role name (argv[1]).\n");
	exit(1);
}

$password = getenv('IEMAP_PASSWORD');
if ($password === false || $password === '') {
	fwrite(STDERR, "render_pgsql_map: IEMAP_PASSWORD environment variable is not set.\n");
	exit(1);
}

// config/Globalvars_site.php sits alongside public_html, four directory levels
// up from this script's provisioning/ directory. An explicit path may be
// passed as argv[2] (install_email.sh passes the one it already resolved).
$config_file = (isset($argv[2]) && $argv[2] !== '') ? $argv[2] : (dirname(__DIR__, 4) . '/config/Globalvars_site.php');

$map = $argv[3] ?? 'domains';
if (!in_array($map, array('domains', 'recipient_access'), true)) {
	fwrite(STDERR, "render_pgsql_map: unknown map '{$map}' (domains or recipient_access).\n");
	exit(1);
}

if (!is_file($config_file) || !is_readable($config_file)) {
	fwrite(STDERR, "render_pgsql_map: cannot read config file: {$config_file}\n");
	exit(1);
}

/**
 * Globalvars_site.php is a list of `$this->settings['key'] = ...;` assignments
 * meant to be require'd inside the Globalvars constructor. Reading it inside a
 * method of this tiny shim reproduces just enough of that context to capture
 * the settings — without loading Globalvars or anything else. Only the
 * non-secret dbname is used; the role credentials come from install_email.sh.
 */
final class GlobalvarsSiteReader {
	public $settings = array();
	public function loadFrom($file) {
		require $file;
	}
}

$reader = new GlobalvarsSiteReader();
$reader->loadFrom($config_file);

$dbname = $reader->settings['dbname'] ?? '';
if ($dbname === '') {
	fwrite(STDERR, "render_pgsql_map: dbname missing from {$config_file}\n");
	exit(1);
}

// The platform's PostgreSQL listens on localhost (see includes/DbConnector.php).
$lines = array();
$lines[] = ($map === 'domains')
	? '# Postfix pgsql map — active inbound email domains.'
	: '# Postfix pgsql access map — the verdict on one recipient address.';
$lines[] = '# Generated by install_email.sh. The password is kept while this file is intact; delete it and re-run to rotate.';
$lines[] = 'hosts = localhost';
$lines[] = 'user = ' . $role;
$lines[] = 'password = ' . $password;
$lines[] = 'dbname = ' . $dbname;
$lines[] = 'query = ' . ($map === 'domains' ? domains_query() : recipient_access_query());

echo implode("\n", $lines) . "\n";
exit(0);

/**
 * The single definition of "active inbound domain"; it must stay aligned with
 * InboundEmailDomain::is_authoritative(): enabled, live, and not the anchor row
 * of a connected Gmail/Outlook feed (gmail.com is never a domain this box
 * receives for). lower() on the column side also covers any row
 * written by a path that bypassed prepare(). The UNION accepts each domain's
 * forwarding subdomain too: the SRS envelope leaves from it
 * (specs/mailbox_send_protection_fix_pack.md, Fix 7), so remote DSNs to
 * SRS0=...@<subdomain> must be deliverable back to the router or bounce
 * handling silently dies.
 */
function domains_query(): string {
	return "SELECT ied_domain FROM ied_inbound_email_domains"
		. " WHERE lower(ied_domain) = '%s' AND ied_is_enabled = true AND ied_delete_time IS NULL AND ied_is_imap_source = false"
		. " UNION SELECT ied_forwarding_subdomain FROM ied_inbound_email_domains"
		. " WHERE lower(ied_forwarding_subdomain) = '%s' AND ied_is_enabled = true AND ied_delete_time IS NULL AND ied_is_imap_source = false";
}

/**
 * The verdict on one recipient, asked while the sending server is still
 * connected, so an address the router would refuse is refused there and the
 * sender's own server tells them. Refused after acceptance instead, Postfix
 * mails a bounce to the message's sender, which on spam is a forged stranger.
 *
 * It reads the rows InboundEmailRouter::processEmail() reads and decides as it
 * does, in its order:
 *
 *   OK      an SRS bounce address on any of our domains (the router's SRS
 *           handling owns it, before any other routing)
 *   OK      an enabled alias on the domain
 *   OK      the domain's catch-all takes it (store, or a forward address)
 *   OK      postmaster, which every mail domain must accept and where our DMARC
 *           reports are sent (the router files a report by its content)
 *   550     the domain refuses unmatched mail and nothing above matched
 *   550     a forwarding subdomain, for anything but an SRS bounce: the router
 *           routes nothing else there
 *   (none)  anything else: the router decides, as for a domain that discards
 *           unmatched mail
 *
 * A lookup Postfix cannot complete (the database is down) is a 4xx, so the
 * sender retries and nothing bounces. Postfix runs the query once per lookup
 * key; %u and %d are empty or suppressed for the keys that are not a full
 * address, so only the full-address lookup answers. %% is a literal %.
 *
 * Its columns are exactly the ones install_email.sh grants the map role.
 */
function recipient_access_query(): string {
	$refuse = "'550 5.1.1 No such address here'";
	return "WITH d AS (SELECT ied_inbound_email_domain_id AS id, ied_catch_all_mode, ied_catch_all_address, ied_reject_unmatched"
		. " FROM ied_inbound_email_domains"
		. " WHERE lower(ied_domain) = lower('%d') AND ied_is_enabled = true AND ied_delete_time IS NULL AND ied_is_imap_source = false),"
		. " f AS (SELECT 1 FROM ied_inbound_email_domains"
		. " WHERE lower(ied_forwarding_subdomain) = lower('%d') AND ied_is_enabled = true AND ied_delete_time IS NULL AND ied_is_imap_source = false)"
		. " SELECT v FROM (SELECT CASE"
		. " WHEN '%u' ILIKE 'srs0=%%' AND (EXISTS (SELECT 1 FROM d) OR EXISTS (SELECT 1 FROM f)) THEN 'OK'"
		. " WHEN NOT EXISTS (SELECT 1 FROM d) THEN CASE WHEN EXISTS (SELECT 1 FROM f) THEN " . $refuse . " END"
		. " WHEN EXISTS (SELECT 1 FROM iea_inbound_email_aliases a JOIN d ON a.iea_ied_inbound_email_domain_id = d.id"
		. " WHERE a.iea_alias = lower('%u') AND a.iea_is_enabled = true AND a.iea_delete_time IS NULL) THEN 'OK'"
		. " WHEN EXISTS (SELECT 1 FROM d WHERE d.ied_catch_all_mode = 'store' OR coalesce(d.ied_catch_all_address, '') <> '') THEN 'OK'"
		. " WHEN lower('%u') = 'postmaster' THEN 'OK'"
		. " WHEN EXISTS (SELECT 1 FROM d WHERE d.ied_reject_unmatched = true) THEN " . $refuse
		. " END AS v) r WHERE v IS NOT NULL";
}
