#!/usr/bin/php
<?php
/**
 * render_pgsql_map.php — prints the Postfix pgsql map that resolves the live
 * list of active inbound email domains.
 *
 * Standalone CLI helper, invoked by install_email.sh. The Postfix map
 * authenticates as a dedicated least-privilege PostgreSQL role (not the
 * application's superuser): install_email.sh creates that role and supplies it
 * here as argv[1], with its password in the IEMAP_PASSWORD environment
 * variable — never argv, so the secret cannot appear in the process list. The
 * only thing read from config/Globalvars_site.php is the non-secret dbname.
 *
 * Output goes to stdout; install_email.sh redirects it into
 * /etc/postfix/joinery-domains.cf and locks the file down (640 root:postfix).
 *
 * Usage:  IEMAP_PASSWORD=... php render_pgsql_map.php <role> [/path/to/Globalvars_site.php]
 *
 * See specs/implemented/email_forwarding_pgsql_credential.md.
 *
 * The map is a live query — Postfix runs it per lookup, so domain AND
 * forwarding-subdomain changes take effect without re-rendering. Re-running
 * install_email.sh (which regenerates this file) is only needed to rotate the
 * role password or pick up a query-shape change like this one.
 *
 * @version 1.3
 */

$role = $argv[1] ?? '';
if ($role === '') {
	fwrite(STDERR, "render_pgsql_map: missing role name (argv[1]).\n");
	exit(1);
}

$password = getenv('IEMAP_PASSWORD');
if ($password === false || $password === '') {
	fwrite(STDERR, "render_pgsql_map: IEMAP_PASSWORD environment variable is not set.\n");
	exit(1);
}

// config/Globalvars_site.php sits alongside public_html, four directory levels
// up from this script's provisioning/ directory. An explicit path may be
// passed as argv[2] (install_email.sh passes the one it already resolved).
$config_file = $argv[2] ?? (dirname(__DIR__, 4) . '/config/Globalvars_site.php');

if (!is_file($config_file) || !is_readable($config_file)) {
	fwrite(STDERR, "render_pgsql_map: cannot read config file: {$config_file}\n");
	exit(1);
}

/**
 * Globalvars_site.php is a list of `$this->settings['key'] = ...;` assignments
 * meant to be require'd inside the Globalvars constructor. Reading it inside a
 * method of this tiny shim reproduces just enough of that context to capture
 * the settings — without loading Globalvars or anything else. Only the
 * non-secret dbname is used; the role credentials come from install_email.sh.
 */
final class GlobalvarsSiteReader {
	public $settings = array();
	public function loadFrom($file) {
		require $file;
	}
}

$reader = new GlobalvarsSiteReader();
$reader->loadFrom($config_file);

$dbname = $reader->settings['dbname'] ?? '';
if ($dbname === '') {
	fwrite(STDERR, "render_pgsql_map: dbname missing from {$config_file}\n");
	exit(1);
}

// The platform's PostgreSQL listens on localhost (see includes/DbConnector.php).
$lines = array();
$lines[] = '# Postfix pgsql map — active inbound email domains.';
$lines[] = '# Generated by install_email.sh; re-run it to rotate the password.';
$lines[] = 'hosts = localhost';
$lines[] = 'user = ' . $role;
$lines[] = 'password = ' . $password;
$lines[] = 'dbname = ' . $dbname;
// This query is the single definition of "active inbound domain" and must
// stay aligned with the InboundEmailDomain model. lower() on the column
// side also covers any row written by a path that bypassed prepare().
// The UNION accepts each domain's forwarding subdomain too: the SRS envelope
// leaves from it (specs/mailbox_send_protection_fix_pack.md, Fix 7), so
// remote DSNs to SRS0=...@<subdomain> must be deliverable back to the router
// or bounce handling silently dies.
$lines[] = "query = SELECT ied_domain FROM ied_inbound_email_domains"
	. " WHERE lower(ied_domain) = '%s' AND ied_is_enabled = true AND ied_delete_time IS NULL"
	. " UNION SELECT ied_forwarding_subdomain FROM ied_inbound_email_domains"
	. " WHERE lower(ied_forwarding_subdomain) = '%s' AND ied_is_enabled = true AND ied_delete_time IS NULL";

echo implode("\n", $lines) . "\n";
exit(0);
